$(document).ready(function(){
    $("#view_grades_button").click(function(){
        $("#main_div").load("./viewgrades/viewgradesview.php");
    });
    $("#new_student_button").click(function(){
        $("#main_div").load("./addstudent/addstudent.html");
    });
    $("#new_grade_button").click(function(){
        $("#main_div").load("./addgrade/addgradeview.php");
    });
});